### PR TITLE
apply for an event badge

### PR DESCRIPTION
**Pull request by thecraftman**
This is the Open draft PR for the Event Badge.

This open draft PR  aims to increase understanding of the open source project and event practices that encourage greater diversity and wider inclusion of people from different backgrounds.

### CODE REVIEW

**Comment by germonprez** [comment]
Thanks @thecraftman Could you please provide a DCO (Developer Certificate of Origin) for signing your PR?

**Comment by thecraftman** [comment]
Thanks @germonprez .  I have added the Developer Certificate of origin (DCO) for signing the PR

**Comment by germonprez** [comment]
Got the DCO. Thanks

**Comment by thecraftman** [comment]
@germonprez  You're welcome

**Comment by ElizabethN** [comment]
@thecraftman :wave:! I think this work is being done in other places, so I'm going to close without merging. Sorry about that! we really appreciate your work here! :pray:

**Comment by thecraftman** [comment]
@ElizabethN thanks. this was the work I did during my outreachy round.

**Pull request closed without merging**
