### PR TITLE
outreachy_microtasks.md

### PR DESCRIPTION
**Pull request by thecraftman**
Signed-off-by: thecraftman <temitopetola@gmail.com>

I've worked on all the microtasks,and my PR is here. Please review it and let me know how it can be improved. 

I will also work on my Outreachy proposal 

Thanks.

### CODE REVIEW

**Comment by bistaastha** [comment]
Hi @thecraftman !
I really like the points you have brought up in your Microtask solutions :)

There's a small thing I wanted to point out, though. I don't think that the file containing the microtask solutions was supposed to be added directly to the badging repository through a PR. Instead, a separate repository has to be created which will contain your microtask solutions, and that has to be linked in the chaoss/governance repository

[chaoss/governance/Outreachy-interest.md](https://github.com/chaoss/governance/blob/master/Outreachy-interest.md)  describes how to do that. It looks almost similar to how I added my work to the governance repository, so I'll write down the steps here:

- Create a repository where you'll keep your microtask solutions
- Add a README.md to link to the microtask solutions (the link could be of a file in the same repository)
- This is the repository which comes under the category of `Micro-Task Repository`, and the link of this repository has to be provided in Outreachy-interest.md
-  As for your proposal document, you have to link a Google doc where you'll keep your final Outreachy proposal

I didn't intend for this to be this lengthy, but I hope I helped :)

Have a good day ahead!

Aastha

**Comment by thecraftman** [comment]
Thanks @bistaastha  for reaching out, this has been helpful. I appreciate

**Comment by ElizabethN** [comment]
I think it's safe to close this PR since this work was completed already.

**Comment by thecraftman** [comment]
@ElizabethN yes and thank you.

**Pull request closed without merging**
